version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3008:3000"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=tododb

  db:
    image: mysql:8
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tododb
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data: