version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/frontend:latest
    ports:
      - "3008:3000"  # Port untuk Next.js app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000  # URL untuk backend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Tambahkan volume jika perlu untuk persistensi data
    # volumes:
    #   - ./backend/data:/app/data

networks:
  default:
    driver: bridge