version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Tambahkan environment variables lain yang diperlukan