name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"  # Tambahkan tanda kutip
          password: "${{ secrets.DOCKER_PASSWORD }}"  # Tambahkan tanda kutip

      - name: Build and push images
        env:  # Gunakan env untuk mengatur environment variables
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml push

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST }}"
          username: "root"
          key: "${{ secrets.SSH_KEY }}"
          script: |
            cd /app/todo-pipeline-demo
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d