version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: humbleboy123/frontend:latest  # Image name untuk Docker Hub
    ports:
      - "3002:3000"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: humbleboy123/backend:latest  # Image name untuk Docker Hub
    ports:
      - "3003:3001"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=tododb


  db:
    image: mysql:8
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tododb
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data: