name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # Build images
          docker compose -f docker-compose.prod.yml build
          
          # Tag images menggunakan environment variable
          docker tag todo-pipeline-demo-frontend ${DOCKER_USERNAME}/frontend:latest
          docker tag todo-pipeline-demo-backend ${DOCKER_USERNAME}/backend:latest
          
          # Push images
          docker push ${DOCKER_USERNAME}/frontend:latest
          docker push ${DOCKER_USERNAME}/backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/todo-pipeline-demo
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d