version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/frontend:latest
    ports:
      - "3005:3000"  # Ubah port host menjadi 3005
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3008  # URL untuk backend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "3008:3008"  # Pastikan port internal dan external sama
    environment:
      - NODE_ENV=production
      - PORT=3008
      
networks:
  default:
    driver: bridge