name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Debug Info
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Docker Username set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "SSH Host set: ${{ secrets.HOST != '' }}"
          echo "SSH Username set: ${{ secrets.SSH_USERNAME != '' }}"
          echo "SSH Key set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            cd /app/todo-pipeline-demo
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            
            # Pull new images
            docker-compose -f docker-compose.prod.yml pull
            
            # Stop and remove existing containers
            docker-compose -f docker-compose.prod.yml down
            
            # Start new containers
            docker-compose -f docker-compose.prod.yml up -d