name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          docker compose build
          docker tag todo-pipeline-demo-frontend humbleboy123/frontend:latest
          docker tag todo-pipeline-demo-backend humbleboy123/backend:latest
          docker push humbleboy123/frontend:latest
          docker push humbleboy123/backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app/todo-pipeline-demo
            docker compose pull
            docker compose down
            docker compose up -d